mode: overfit # train , test ,export ,overfit
distributed_lr: False 
random_seed: 42
trial_name: roi_segmentation_overift

#model and data:
model: U_Net #available models : U_Net ,SMP
batch_size: 1
in_channels: 1
out_channels: 2
fmaps: 16 #in case of using U_Net
dropout: 0.4
input_size: 512
train_validate_ratio: 0.5
test_validate_ratio: 0.5
dataset_version: False #v1.0 #False #roi-dataset-1.0

#hyperparameters:
epochs: 5
log_period: 1
learning_rate: 0.02
criterion: CrossEntropyLoss
optimizer: Adam
augment: False

#training
auto_cast: False #using grad scaler to apply mixed precession
clip_grad: False #to prevent exploding gradients
use_lr_scheduler: True # (Step , Cosine , linear ,inverse sqrt) to update the learning rate during training
lr_scheduler_gamma: 0.1

#paths :
dataset_path: D:\cases_dicom\chest_x-ray\dataset
test_dataset_path: D:\cases_dicom\chest_x-ray\test_set
weights_path: D:\Code_store\x-ray_segmentation\results\unet.pth
results_path: D:\Code_store\x-ray_segmentation\results
